on:
  push:
    branches: [ dev ]

name: Create Binaries
jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        include:
          - os: ubuntu-latest
            name: Ubuntu
          - os: windows-latest
            name: Windows
          - os: macOS-latest
            name: macOS
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install requirements
        run: pip install -r requirements.txt PyInstaller
      - name: Run PyInstaller
        run: pyinstaller --onefile -n arXiv-sorter-${{ matrix.name }} main.py
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: arXiv-sorter-${{ matrix.name }}
          path: dist/
      - name: Test
        run: |
          dist/arXiv-sorter-${{ matrix.name }}


  create_release:
    needs: [ build ]
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: New release
          draft: true
          prerelease: false
          tag_name: v0.0.0

      - name: Load binaries
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Flatten binaries
        run: mv artifacts/*/* ./

      - name: Upload Release Assets
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: arXiv-sorter-*