on:
  push:
    branches: [ dev ]

#on:
#  release:
#    types: [ created ]

name: Create Binaries
jobs:
  build_linux:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: pip install -r requirements.txt PyInstaller
      - name: Run PyInstaller
        run: pyinstaller --onefile -n arXiv-sorter-linux main.py
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: arXiv-sorter-linux
          path: dist/arXiv-sorter-linux
      - name: Test
        run: dist/arXiv-sorter-linux

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: pip install -r requirements.txt PyInstaller
      - name: Run PyInstaller
        run: pyinstaller --onefile -n arXiv-sorter-windows.exe main.py
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: arXiv-sorter-windows.exe
          path: dist/arXiv-sorter-windows.exe
      - name: Test
        run: dist/arXiv-sorter-windows.exe

  build_macos:
    name: Build MacOc
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: pip install -r requirements.txt PyInstaller
      - name: Run PyInstaller
        run: pyinstaller --onefile -n arXiv-sorter-macos main.py
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: arXiv-sorter-macos
          path: dist/arXiv-sorter-macos
      - name: Test
        run: dist/arXiv-sorter-macos


  create_release:
    needs: [ build_linux, build_windows, build_macos ]
    name: Create release
    runs-on: ubuntu-latest
    steps:
      #      - name: Create Release
      #        id: create_release
      #        uses: actions/create-release@v1
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #        with:
      #          release_name: New release
      #          draft: true
      #          prerelease: false
      #          tag_name: v0.0.0

      - name: Get last release
        id: get_last_release
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Get last release
#        id: get_last_release
#        uses: pozetroninc/github-action-get-latest-release@master
#        with:
#          owner: JohnSully
#          repo: KeyDB
#          excludes: prerelease, draft


      - name: Load binaries
        uses: actions/download-artifact@v3

      - name: Upload Release Assets
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_last_release.outputs.upload_url }}
          asset_path: arXiv-sorter-*
