on:
  push:
    branches: dev

#on:
#  workflow_dispatch:

#on:
#  release:
#    types: [created]

name: Create Binaries
jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: pip install -r requirements.txt PyInstaller
      - name: Run PyInstaller
        run: PyInstaller --onefile -n arXiv-sorter-windows.exe main.py
      - name: Files
        run: ls
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
#      - name: Upload the artifacts
#        uses: skx/github-action-publish-binaries@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          args: 'example-*'