name: Build Workflow

# on:
#   push:
# #    branches: master

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: pip install -r requirements.txt PyInstaller
      - name: Run PyInstaller
        run: python -m PyInstaller main.py
